version: '3.8'

services:
  nuxt:
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}:${TAG:-main}
    platform: linux/amd64
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - APP_ENV=${APP_ENV:-production}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    restart: unless-stopped


