version: '3.8'

services:
  wallet-nuxt-dev:
    image: uvend/uvend-wallet-nuxt:development
    platform: linux/amd64
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    env_file:
      - .env
    restart: unless-stopped
networks: {}